### ISSUE TITLE
Not present the booting view of disk.img 

### ISSUE THREAD

**Issue by stardustman** [o8vm/krabs#27]
**Describe the bug**
I have compiled the source code and prepared the disk.img. The partitation for disk.img has completed.
But when I ` run cargo run -- -w disk.img -e`,the result is:
```bash
star@node:~/krabs$ cargo run -- -w disk.img -e
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/krabs -w disk.img -e`
Checking the first [4] stage(s) build...
    Build exists. Builds { stage_1st: Some("/home/star/krabs/target/stage_1st/i586-stage_1st/release/stage_1st.bin"), stage_2nd: Some("/home/star/krabs/target/stage_2nd/i586-stage_2nd/release/stage_2nd.bin"), stage_3rd: Some("/home/star/krabs/target/stage_3rd/i586-stage_3rd/release/stage_3rd.bin"), stage_4th: Some("/home/star/krabs/target/stage_4th/i586-stage_4th/release/stage_4th.bin") }
Checking partitions...
    BIOS boot partition: start = 2048, end = 4095
    EFI System Partition: start = 4096, end = 106495
Burn each stage to disk....
    stage_1st...  done.
    stage_2nd...  done
    stage_3rd...  done
    stage_4th...  done
Try qemu...
```
There is `no booting view` of the disk.img?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
What is the reason?

**Comment by o8vm** [comment]
Do you have the qemu-system-x86 package installed on your system?

```shell
sudo apt install qemu-system-x86
```
If you have qemu-system-x86 installed, try the `disk.img` in [this repository](https://github.com/o8vm/sandylinux).  
This is a very sample linux image for testing this bootloader.

```shell
git clone https://github.com/o8vm/sandylinux.git
cd /path/to/krabs
cargo run -- -w /path/to/disk.img -e
```

**Comment by stardustman** [comment]
![image](https://user-images.githubusercontent.com/22998204/95071687-a7d33100-073c-11eb-8023-c10ca7806e90.png)
Hello，I have installed the qemu-system-86. I use the disk.img you provided, But I run `cargo run -- -w ../sandylinux/disk.img -e` at krabs directory, I still can't find the booting view. The OS I use is ubuntu-20.04.1-live-server-amd64 runing in virtual box.
rustc version is 1.46.0 (04488afe3 2020-08-24).

**Comment by stardustman** [comment]
I think I found the reason, I use ssh to connect the vm, the OS I use (not contained the GUI)didn't support to generate new bash window. I have sucessed to see the booting window.
